# Generated by Django 4.2.10 on 2025-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedimage',
            name='used_reference_image',
            field=models.BooleanField(default=False),
        ),
    ]
