# Generated by Django 4.2.10 on 2025-04-04 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aigc', '0002_aigeneratedimage_used_reference_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Attribute Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=1.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aigc.attribute')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aigc.aigeneratedimage')),
            ],
            options={
                'unique_together': {('image', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='aigc.attributecategory'),
        ),
        migrations.AddField(
            model_name='aigeneratedimage',
            name='attributes',
            field=models.ManyToManyField(related_name='images', through='aigc.ImageAttribute', to='aigc.attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('category', 'name')},
        ),
    ]
