# Generated by Django 4.2.10 on 2025-03-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField()),
                ('source_url', models.URLField()),
                ('listing_type', models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures'), ('perpetual', 'Perpetual'), ('margin', 'Margin'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('region', models.CharField(choices=[('SG', 'Singapore'), ('TR', 'Turkey')], max_length=5)),
                ('raw_date_str', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Listing',
                'verbose_name_plural': 'Token Listings',
                'ordering': ['-publication_date'],
                'unique_together': {('symbol', 'listing_type', 'region')},
            },
        ),
    ]
