# Generated by Django 4.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyzrTokenAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lyzr Token Analysis',
                'verbose_name_plural': 'Lyzr Token Analyses',
                'ordering': ['-timestamp'],
            },
        ),
    ] 